//Passwords are generated by antrun goal in the build
//There are two runs of this build, once with the default 'extensions-disabled' profile which
//sets extension version to 'disabled' which is a special value that does not enable the extension
//and a second run which sets the extension version through a property which enables it
File serversEnabledPasswordsFile = new File(basedir, 'target/servers-enabled.properties')
Properties serversEnabledPasswords = new Properties()
serversEnabledPasswordsFile.withInputStream {
    serversEnabledPasswords.load(it)
}

assert serversEnabledPasswords.testServerUser == 'test-user'
assert serversEnabledPasswords.testServerPassword == 'test-password'



File serversDisabledPasswordsFile = new File(basedir, 'target/servers-disabled.properties')
Properties serversDisabledPasswords = new Properties()
serversDisabledPasswordsFile.withInputStream {
    serversDisabledPasswords.load(it)
}

//Both values should remain uninterpolated since extension should not have loaded for this one
assert serversDisabledPasswords.testServerUser == '${settings.servers.testServer.username}'
assert serversDisabledPasswords.testServerPassword == '${settings.servers.testServer.password}'