//Passwords are generated by antrun goal in the build, and will only work if the servers extension is loaded
//The servers extension is only loaded because our user-extensions extension loads it from .m2/extensions.xml

File serverPasswordsFile = new File(basedir, 'target/server-passwords.properties')
Properties serverPasswords = new Properties()
serverPasswordsFile.withInputStream {
    serverPasswords.load(it)
}

assert serverPasswords.testServerUser == 'test-user'
assert serverPasswords.testServerPassword == 'test-password'
